language: node_js
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm build

deploy:
  provider: surge
  cleanup: true
  project: ./build/
  domain: tdd-demo.surge.sh
  on:
    branch: master
